### ISSUE TITLE
Checked the script for static analysis 

### ISSUE THREAD

**Issue by Sim4n6** [atarallo/TECMINT_MONITOR#17]
I shellchecked the script for static analysis. please check the last commit of the pull request #16. thank you

**Comment by atarallo** [comment]
It's a very good idea you had. Good job. I think that this should be done on the DEVELOPMENT branch. Some of the issues you detected I've corrected there. 

Fill free to let me know what you think about.

**Comment by Sim4n6** [comment]
cool, :+1: I will shellcheck again the script in the dev branch tonight !

**Comment by Sim4n6** [comment]
PR #18 for Shellchecking first step
