### ISSUE TITLE
Tag for a version reference

### ISSUE THREAD

**Issue by Sim4n6** [atarallo/TECMINT_MONITOR#22]
Hi contributors, 

I think after the shellcheck static analysis of the script, it is time to release a tag v0.2 of the script . A kind of reference code that we should not break, 

Have a nice weekend

**Comment by atarallo** [comment]
For me it's Ok.

**Comment by Sim4n6** [comment]
`git tag -a v0.2 -m "version 0.2"`
`git push origin v0.2`

you are the owner of the repo, it is up to you to do it :-)

**Comment by atarallo** [comment]
Added the tag, as requested.

**Comment by Sim4n6** [comment]
awesome, let's tag each major version of this script :+1:
