### ISSUE TITLE
lsb_release first

### ISSUE THREAD

**Issue by Sim4n6** [atarallo/TECMINT_MONITOR#23]
I am doing some research to figure out the best way to extract the distributions information.

I have found the Linux Standard Base (LSB). : 

> _The Linux Standard Base is a project under the Free Standards Group. It attempts to develop and promote a set of binary standards that will increase compatibility among GNU/Linux and other similar systems. These standards will also enable software applications to run on any conforming system._
> 
> _While the main goal of the LSB project is to increase compatibility among GNU/Linux distributions by specifying and promoting standards for their use, it does not limit the applicability of the specification to only the GNU/Linux environment. The LSB specification has been written so that it can be readily implemented on any UNIX-like operating system, natively or as a compatibility layer. With some more work, it can also be implemented on other operating systems._

Any distribution that supports **Linux Standard Base Core Specification 3.1** will contain :  
a command **_lsb_release_** that prints certain LSB (Linux Standard Base) and Distribution information in a normalized way. 

So I suggest to use it first in the script before checking any other information about the distos.

**Comment by atarallo** [comment]
It could be a good idea to change the code we're actually using for something based on LSB for Linux.

**Comment by Sim4n6** [comment]
assign it to me please :+1:

**Comment by atarallo** [comment]
As requested, asssigned to you.

**Comment by Sim4n6** [comment]
the idea in  #25 is to use lsb_release in case it is available, 
please I checked the script on Ubuntu GNU/Linux 16.04 not other distos

**Comment by atarallo** [comment]
I looked your contribution. Good Job! I'll be testing it on my PCs
