### ISSUE TITLE
live monitoring 

### ISSUE THREAD

**Issue by Sim4n6** [atarallo/TECMINT_MONITOR#27]
I have an idea : why not make `-l` option for live monitoring, open for discussion

**Comment by arthar360** [comment]
Our script is showing majority of data which is static. The only dynamic data is of RAM, swap, disk usage, uptime and logged in users. All this can be monitored in detailed using the top, htop or atop command. Adding -l seems a nice idea but I don't think it will be that helpful and detailed monitoring as by using above commands.

**Comment by Sim4n6** [comment]
okey, interesting point of view, 
waiting for @atarallo opinion

**Comment by atarallo** [comment]
I envision this script as tool for retrieving data in a certain instant of time. The name "techmint_monitor" is misleading, but was inherited from the original author (The techmint website). 

I think in this script more as tool to retrieve many relevant data easily, than a monitoring tool. But I don't mind adding the proposed switch. 

A switch that I might find useful is one that dumps the output as ASCII text. this kind of tools are helpful for technicians that might need relevant data for their work.

**Comment by Sim4n6** [comment]
According to the license (Apache) applied to the script, we can modify and distribute the script. In other words, we only have to, according to the Apache license, include a copy of the original license and a notice of the modified files (in our case it is just one). So, we can change the name of the script. 

The way you perceive the utility of the script is interesting : a kind of a static visualization of some main information.

**Comment by Sim4n6** [comment]
In order to dump the output as ASCII text , the user can simply do `bash tecmint_script > test.temp` and then `less -R test.temp` 

we need to add this last as a tip to the README right ? :+1:
