### ISSUE TITLE
OS variable used twice 

### ISSUE THREAD

**Issue by Sim4n6** [atarallo/TECMINT_MONITOR#28]
OS variable used twice with uname -s and uname -o , please check that

**Comment by atarallo** [comment]
Both switches output different information.  The -s outputs the kernel name. The -o outputs the operating systems name. 

The OS variable is loaded first with the kernel name, this is used to load other variables. Latter is used to output the Operating system name. 

Maybe we should load the data in separated variables.

**Comment by Sim4n6** [comment]
right, in separated variables, just renaming  one , either the  first or the last, it is up to you
